import nacl from "tweetnacl";
import { bytesToHex, hexToBytes, utf8ToBytes, bytesToUtf8 } from "./crypto";

/**
 * Offline license verification (Ed25519 via tweetnacl).
 *
 * License format:  HEX(payloadUtf8) . HEX(signature)
 * Payload:         v1|id|type|issued|expires|device|name
 *
 * The app embeds only the PUBLIC key (safe to ship). The seller keeps the
 * private key and generates keys via scripts/license-tool.mjs.
 */

export type LicenseType = "standard" | "pro" | "lifetime";

export interface LicenseInfo {
  valid: boolean;
  /** Why it failed, if not valid */
  reason?: "bad_format" | "bad_signature" | "expired" | "device_mismatch";
  id?: string;
  type?: LicenseType;
  issued?: number;
  expires?: number; // unix seconds; 0 = never
  device?: string; // device code this key is bound to ("" = any device)
  name?: string;
}

const VERSION = "v1";
const DELIM = "|";

/** Public key — generated by the seller (scripts/license-tool.mjs --init).
 *  Only this key ships with the app; it cannot forge licenses. */
import { LICENSE_PUBLIC_KEY } from "./license-public";

function parsePayload(str: string) {
  const parts = str.split(DELIM);
  if (parts.length < 7 || parts[0] !== VERSION) return null;
  const [, id, type, issued, expires, device, ...nameParts] = parts;
  return {
    id,
    type: type as LicenseType,
    issued: Number(issued),
    expires: Number(expires),
    device: device ?? "",
    name: nameParts.join(DELIM) ?? "",
  };
}

/** Verify a license key against the embedded public key + current device. */
export function verifyLicense(
  key: string,
  expectedDeviceCode?: string
): LicenseInfo {
  const clean = key.trim().replace(/\s+/g, "");
  const dot = clean.indexOf(".");
  if (dot < 0) return { valid: false, reason: "bad_format" };

  const payloadHex = clean.slice(0, dot);
  const sigHex = clean.slice(dot + 1);
  if (!payloadHex || !sigHex) return { valid: false, reason: "bad_format" };

  let payloadBytes: Uint8Array;
  let signature: Uint8Array;
  let payloadStr: string;
  try {
    payloadBytes = hexToBytes(payloadHex);
    signature = hexToBytes(sigHex);
    payloadStr = bytesToUtf8(payloadBytes);
  } catch {
    return { valid: false, reason: "bad_format" };
  }

  const parsed = parsePayload(payloadStr);
  if (!parsed) return { valid: false, reason: "bad_format" };

  // Verify Ed25519 signature
  const publicKey = hexToBytes(LICENSE_PUBLIC_KEY);
  let ok: boolean;
  try {
    ok = nacl.sign.detached.verify(utf8ToBytes(payloadStr), signature, publicKey);
  } catch {
    return { valid: false, reason: "bad_signature" };
  }
  if (!ok) return { valid: false, reason: "bad_signature" };

  // Expiry
  if (parsed.expires !== 0 && Date.now() / 1000 > parsed.expires) {
    return { ...parsed, valid: false, reason: "expired" };
  }

  // Device binding
  if (parsed.device && expectedDeviceCode && parsed.device !== expectedDeviceCode) {
    return { ...parsed, valid: false, reason: "device_mismatch" };
  }

  return { ...parsed, valid: true };
}

export function isLicensed(info: LicenseInfo | null | undefined): boolean {
  return Boolean(info && info.valid);
}

/** Human-readable description of a verified license for the settings screen. */
export function describeLicense(info: LicenseInfo): string {
  if (!info.valid) return "—";
  const exp =
    !info.expires || info.expires === 0
      ? "Lifetime"
      : new Date(info.expires * 1000).toLocaleDateString();
  return `${info.type ?? "standard"} · ${exp}`;
}

// Re-export for the generator tool convenience
export { bytesToHex };
