#!/usr/bin/env node
/**
 * License key generator (SELLER ONLY).
 *
 * Usage:
 *   node scripts/license-tool.mjs init
 *       Generates a new keypair. Writes the public key into the app
 *       (src/lib/license-public.ts) and saves your PRIVATE key to
 *       scripts/license-private.json — KEEP THIS FILE SECRET and never
 *       commit/push it (it's gitignored).
 *
 *   node scripts/license-tool.mjs gen --name "Ahmed Ali" --type pro --days 365
 *       Creates a license key for a customer. Print it and send to the buyer.
 *       --type: standard | pro | lifetime
 *       --days: validity in days. Omit for a never-expiring key.
 *       --device ABCD1234: bind the key to one device (customer sends their
 *           device code from the app's activation screen).
 */
import nacl from "tweetnacl";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const PRIVATE_PATH = resolve(ROOT, "scripts/license-private.json");
const PUBLIC_TS_PATH = resolve(ROOT, "src/lib/license-public.ts");

const VERSION = "v1";
const bytesToHex = (b) => Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
const utf8 = (s) => new TextEncoder().encode(s);

function loadPrivate() {
  if (!existsSync(PRIVATE_PATH)) {
    console.error("\n✖ No private key found. Run `node scripts/license-tool.mjs init` first.\n");
    process.exit(1);
  }
  const json = JSON.parse(readFileSync(PRIVATE_PATH, "utf8"));
  return { publicKey: hexToBytes(json.publicKey), secretKey: hexToBytes(json.secretKey) };
}

function hexToBytes(hex) {
  const out = new Uint8Array(Math.floor(hex.length / 2));
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(i * 2, 2), 16);
  return out;
}

function cmdInit() {
  const kp = nacl.sign.keyPair();
  const data = {
    created: new Date().toISOString(),
    publicKey: bytesToHex(kp.publicKey),
    secretKey: bytesToHex(kp.secretKey),
    note: "KEEP SECRET. Whoever holds secretKey can generate license keys for the app.",
  };
  writeFileSync(PRIVATE_PATH, JSON.stringify(data, null, 2) + "\n");
  const ts = `// AUTO-GENERATED by scripts/license-tool.mjs — safe to ship (public key only).\nexport const LICENSE_PUBLIC_KEY = "${data.publicKey}";\n`;
  writeFileSync(PUBLIC_TS_PATH, ts);
  console.log("\n✔ Keypair generated.");
  console.log(`  Public key  → src/lib/license-public.ts (ships with the app)`);
  console.log(`  Private key → scripts/license-private.json (SECRET — do not share/commit)\n`);
}

function cmdGen(args) {
  const get = (k) => {
    const i = args.indexOf(k);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const name = get("--name") ?? "";
  const type = get("--type") ?? "pro";
  const days = get("--days");
  const device = get("--device") ?? "";

  const kp = loadPrivate();
  const issued = Math.floor(Date.now() / 1000);
  const expires = days ? issued + Number(days) * 86400 : 0;
  const id = "LIC-" + bytesToHex(nacl.randomBytes(3)).toUpperCase();

  const payload = [VERSION, id, type, issued, expires, device, name].join("|");
  const sig = nacl.sign.detached(utf8(payload), kp.secretKey);
  const key = bytesToHex(utf8(payload)) + "." + bytesToHex(sig);

  const expiryStr = expires === 0 ? "NEVER (lifetime)" : new Date(expires * 1000).toISOString().slice(0, 10);
  console.log("\n──────────────────────────────────────────────");
  console.log("  NEW LICENSE KEY");
  console.log("──────────────────────────────────────────────");
  console.log(`  Customer : ${name || "(none)"}`);
  console.log(`  ID       : ${id}`);
  console.log(`  Type     : ${type}`);
  console.log(`  Expires  : ${expiryStr}`);
  if (device) console.log(`  Device   : ${device}`);
  console.log("\n  Send this key to the customer:\n");
  console.log("  " + key);
  console.log("\n──────────────────────────────────────────────\n");
}

const [, , sub, ...rest] = process.argv;
if (sub === "init") cmdInit();
else if (sub === "gen") cmdGen(rest);
else {
  console.log("\nUsage:\n  node scripts/license-tool.mjs init\n  node scripts/license-tool.mjs gen --name \"..\" --type pro --days 365 [--device CODE]\n");
}
